### ISSUE TITLE
Question - can I save the images to S3?

### ISSUE THREAD

**Issue by zulhfreelancer** [ThalKod/DropIt#2]
Hi,

This project really looks cool!

I've a question here. Can I store the images to S3?
How? Do you have sample code for that?

Thank you.

**Comment by ThalKod** [comment]
You mean Using  [aws-sdk](https://aws.amazon.com/sdk-for-node-js/) to upload files ?

**Comment by zulhfreelancer** [comment]
Yes, correct. Possible?

**Comment by ThalKod** [comment]
Yes, it's possible.

**Comment by zulhfreelancer** [comment]
Can you please share the steps?

**Comment by ThalKod** [comment]
You can checkout [this ](https://stackoverflow.com/questions/17930204/simple-file-upload-to-s3-using-aws-sdk-and-node-express), it's pretty straightforward...

**Comment by zulhfreelancer** [comment]
Thanks.
