### ISSUE TITLE
Arbitrary file overwrite vulnerability

### ISSUE THREAD

**Issue by micaksica2** [ThalKod/DropIt#3]
The file upload process appears vulnerable to file overwrite because the original filenames are preserved and all uploaded files are dumped into a `files/` directory. The application should not trust input from an external source, and should parse it appropriately.

See [line 15](https://github.com/ThalKod/DropIt/blob/master/app.js#L15), in which the `file.originalname` (untrusted input) is used as the name of the file on disk. multer strips path characters from the filename="" in the multipart upload so you get restricted to the files/ directory, but if you know the name of any other file you can clobber it with your own with a filename collision in the filename="" part of the multipart upload.

This is an explicit override of [the multer diskStorage callback](https://github.com/expressjs/multer/blob/master/storage/disk.js#L8) which does this random filename generation for this reason. 

Remember, file upload is dangerous. [Please review OWASP for more information.](https://www.owasp.org/index.php/Unrestricted_File_Upload)

**Comment by ThalKod** [comment]
Thanks, i'll look into this.
