### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'count' of undefined

### ISSUE THREAD

**Issue by dungphanxuan** [ThalKod/DropIt#5]
![image](https://user-images.githubusercontent.com/10725732/41187227-1d3976c2-6bcf-11e8-8255-7d4df0551a7c.png)

**Comment by ashraful-islam** [comment]
@ThalKod Looks like Count was just passed as object instead of first being defined as mongoose.Schema. Also there are null access in most routes.

@ThalKod added a fix here https://github.com/ThalKod/DropIt/pull/6/commits/b6ced4cb471237f2151d350da5d8571d8613ce6e 😄

**Comment by ThalKod** [comment]
@dungphanxuan mostly due to the fact that there's no Count document at the first run... now fixed...
@ashraful-islam Great !
