### ISSUE TITLE
Upload max size

### ISSUE THREAD

**Issue by dungphanxuan** [ThalKod/DropIt#7]
I set max size so notify will return
![image](https://user-images.githubusercontent.com/10725732/41265303-bc72392e-6e1b-11e8-9e7b-5ab587d97250.png)

**Comment by dungphanxuan** [comment]
![image](https://user-images.githubusercontent.com/10725732/41270287-8ee045e6-6e34-11e8-9bb1-403601e66400.png)

**Comment by ThalKod** [comment]
it's actually maxFilesize not maxFileSize for setting up the max size, Fixed.
